name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/markosagadin/ncs-docker-setup/ncs-v1.8.0-docky:latest
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: project

      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-west-modules
        with:
          path: |
            bootloader
            mbedtls
            modules
            nrf
            nrfxlib
            test
            tools
            zephyr
          key: ${{ runner.os }}-build-v2-${{ env.cache-name }}-${{ hashFiles('project/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Initialize West manifest directory
        run: west init -l project

      - name: Update West manifest directory
        run: |
          west update

      - name: Build firmware
        run: |
          west build -b custom_plank -s project/app

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: build/zephyr/zephyr.*
